name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} ${{ DOCKERHUB_SERVER }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ DOCKERHUB_SERVER }}/mibridge
    - name: Push the Docker image
      run: docker push ${{ DOCKERHUB_SERVER }}/mibridge
